//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MSerialsUI.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_SYSCTRL                     101
#define IDD_CAMERA2                     101
#define IDD_CAMERA1                     102
#define IDD_RS232                       103
#define IDD_SETTINGS                    104
#define IDD_VERITY                      105
#define IDD_DATA_LOOKUP                 106
#define IDD_HISTORY                     107
#define IDD_STATICS_DATA                108
#define IDD_VERITY_ACCESS               109
#define IDB_WRITESMALL                  110
#define IDD_VERITY_ACCESS_TEST          110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MSerialsUITYPE              130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDC_EDIT_INPUT                  1000
#define IDC_BUTTON_COMFIRM              1001
#define IDC_STATIC_INPUTSTR             1002
#define IDC_BUTTON_CLOSEPORT            1002
#define IDC_BUTTON_LOADPIC              1003
#define IDC_BUTTON_DRAW_RECT            1003
#define IDC_BUTTON_DRAW_RECT2           1003
#define IDC_BUTTON_RELOADSCRIPT         1004
#define IDC_BUTTON_SAVE                 1004
#define IDC_BUTTON_DRAW_GET_VENODR      1004
#define IDC_BUTTON_READIMG1             1005
#define IDC_COMBO_PRJ_SEL               1005
#define IDC_COMBO_COMSEL                1006
#define IDC_BUTTON_DEAL_TEST            1006
#define IDC_BUTTON1                     1007
#define IDC_BUTTON_REFRESHCAM           1007
#define IDC_BUTTON_APPLICATE            1007
#define IDC_BUTTON_SHOW_RECT            1007
#define IDC_BUTTON_COMFIRM_SECRET       1007
#define IDC_BUTTON_SAVEIMAGE            1008
#define IDC_BUTTON_REFRESHCAM2          1008
#define IDC_BUTTON_SAVEPARAPRJ          1008
#define IDC_BUTTON_SNAP1                1009
#define IDC_BUTTON_DEL_PRJ              1009
#define IDC_STATIC_INDICATE             1010
#define IDC_BUTTON_SAVEASF              1010
#define IDC_EDIT_NEWPRJ                 1011
#define IDC_BUTTON_SAVEASB              1011
#define IDC_COMBO_SRC                   1012
#define IDC_EDIT_SNAPDELAY              1012
#define IDC_BUTTON_OPENF                1012
#define IDC_TRAIN                       1013
#define IDC_EDIT_EXPLOSURE              1013
#define IDC_BUTTON_OPENB                1013
#define IDC_COMBO_DST                   1014
#define IDC_BUTTON_TRYTRAIN             1014
#define IDC_EDIT_ACCURCY                1014
#define IDC_BUTTON_OPENB2               1014
#define IDC_BUTTON_SAVEIMAGEINCHECK     1014
#define IDC_BUTTON_BREADIMG             1015
#define IDC_BUTTON_SAVEACC              1015
#define IDC_BUTTON_BDEAL_TEST           1016
#define IDC_BUTTON_BSAVEIMAGE           1017
#define IDC_BUTTON_DRAW_BRECT           1018
#define IDC_BUTTON_SHOW_BRECT           1019
#define IDC_BUTTON_TRAIN_IMAGES         1020
#define IDC_BUTTON_SAVE_MODEL           1020
#define IDC_BUTTON_PREDICT              1021
#define IDC_BUTTON_READ_MODEL           1021
#define IDC_BUTTON_DRAW_TEST_PIC        1022
#define IDC_BUTTON_SNAP2                1023
#define IDC_EDIT_THRESHOLD_VALUE        1024
#define IDC_BUTTON_READ_MODEL2          1025
#define IDC_BUTTON_READ_MODEL3          1026
#define IDC_BUTTON_SAVE_PARA2           1027
#define IDC_BUTTON_READ_MODEL4          1028
#define IDC_BUTTON_READ_MODEL5          1029
#define IDC_BUTTON_CLEAR_MODEL          1030
#define IDC_STATIC_MODEL_NUM            1031
#define IDC_EDIT1                       1032
#define IDC_EDIT_PASSWORD               1033
#define IDC_BUTTON_STATISTIC            1034
#define IDC_BUTTON_HISTORY_DATA         1035
#define IDC_STATIC_DATA_SHOW            1039
#define IDC_EDIT3                       1040
#define IDC_EDIT_HISTORTY               1040
#define IDC_BUTTON_OK                   1041
#define IDC_BUTTON_CANCEL               1042
#define IDC_EDIT_PWD                    1043
#define IDC_EDIT_SERIAL                 1044
#define IDC_BUTTON_CAL                  1045
#define IDC_EDIT_SERIAL_T               1046
#define IDC_EDIT_PWD_T                  1047
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON_TEST                  32771
#define ID_BUTTON_TEST2                 32772
#define ID_BUTTON_SETTINGS              32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        312
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
